title: Mommy Tree
email: anntropea@gmail.com
description: >-
  Baltimore doula support that grows with you. Birth doula services, childbirth education,
  and breastfeeding support.
url: "https://mommytreedoula.com"
baseurl: ""
share_image: "/assets/images/hero/hero.jpg"
google_analytics_id: "G-559NCC68VP"
markdown: kramdown

# Build settings
plugins: []
